### ISSUE TITLE
Adopt cpp guidelines

### ISSUE THREAD

**Issue by luizperes** [luizperes/brain#4]
Make code refactoring to follow the [CppCoreGuidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md) as described [here](http://www.stroustrup.com/bs_faq2.html)

**Comment by rafaelcn** [comment]
Perfect! I would love use Stroustrup guidelines.

**Comment by rafaelcn** [comment]
We ended up using some mixed code style, but it is quite good, we have to focus to write good C++ as shown [here]( https://www.youtube.com/watch?v=1OEu9C51K2A&index=1&list=PLHTh1InhhwT75gykhs7pqcR_uSiG601oh) and in other videos from _CppCon_. Anyway, closing this issue because there is not any reason to keep it open, feel free to reopen it.
